version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - python -m pip install pipx
      - python -m pipx ensurepath
      - pipx install poetry==1.2.0b1
      - poetry config virtualenvs.create false
      - poetry install --with docs
sphinx:
  configuration: docs/conf.py
formats: all
