version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry self add poetry-plugin-export
      - poetry export --with docs --output requirements.txt
      - pip install -r requirements.txt
      - pip install  -e .
sphinx:
  configuration: docs/conf.py
formats: all
